version: '3'
services:
  nginx:
    container_name: v-crm-nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 8081:80
      - 8082:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=v-crm.dev
    networks:
      - v-crm
  php:
    container_name: v-crm-php
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    restart: always
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html
    networks:
      - v-crm
  db:
    container_name: v-crm-mysql
    hostname: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpwd
      - MYSQL_ROOT_PASSWORD=dbpwd
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - v-crm

  php-tasks:
    container_name: v-crm-tasks
    environment:
      - MYSQL_HOST=db
    build:
      context: ./
      dockerfile: docker/php-tasks/Dockerfile
    restart: always
    ports:
      - '1338'
    volumes:
      - /home/fnc/tasks/:/var/www/html
    networks:
      - v-crm

  sqlipt2:
    container_name: sqlipt2
    environment:
      - MYSQL_HOST=db
    build:
      context: ./
      dockerfile: docker/php-tasks/Dockerfile
    restart: always
    ports:
      - '1339'
    volumes:
      - /home/fnc/sqlipt2/:/var/www/html
    networks:
      - v-crm

  sqli_union:
    container_name: sqli_union
    environment:
      - MYSQL_HOST=db
    build:
      context: ./
      dockerfile: docker/php-tasks/Dockerfile
    restart: always
    ports:
      - '1340'
    volumes:
      - /home/fnc/sqli_union/:/var/www/html
    networks:
      - v-crm

  nginx-tasks:
    container_name: v-crm-nginx-tasks
    image: nginx:latest
    restart: always
    ports:
      - 1337:80
      - 1339:8081
      - 1340:8082
    volumes:
      - /home/fnc/nginx-tasks/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/fnc/tasks/:/var/www/html
    networks:
      - v-crm

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 9090:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - v-crm

networks:
  v-crm:
    driver: bridge

volumes:
  mysql_data:
